# Generated by Django 5.1.3 on 2025-05-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='representante',
            field=models.CharField(default='Representante Desconocido', max_length=100, verbose_name='Representante Legal'),
        ),
    ]
