# Generated by Django 5.1.3 on 2025-06-01 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0002_empresas_representante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='estado_monitoreo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='nivel_seguridad',
            field=models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='MEDIO', max_length=20),
        ),
        migrations.AddField(
            model_name='empresas',
            name='ultimo_escaneo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='representante',
            field=models.CharField(max_length=100, verbose_name='Representante Legal'),
        ),
        migrations.CreateModel(
            name='Amenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MALWARE', 'Malware'), ('PHISHING', 'Phishing'), ('RANSOMWARE', 'Ransomware'), ('DOS', 'Denegación de Servicio'), ('OTRO', 'Otro')], max_length=20)),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('detalles_tecnicos', models.JSONField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenazas', to='Crud.empresas')),
            ],
            options={
                'verbose_name': 'Amenaza',
                'verbose_name_plural': 'Amenazas',
                'ordering': ['-fecha_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escaneo_automatico', models.BooleanField(default=True)),
                ('frecuencia_escaneo', models.IntegerField(default=24, help_text='Frecuencia en horas')),
                ('notificar_amenazas', models.BooleanField(default=True)),
                ('nivel_alertas', models.CharField(choices=[('TODAS', 'Todas las alertas'), ('MEDIA_ALTA', 'Media y Alta'), ('ALTA', 'Solo Alta')], default='MEDIA_ALTA', max_length=20)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='Crud.empresas')),
            ],
            options={
                'verbose_name': 'Configuración de Monitoreo',
                'verbose_name_plural': 'Configuraciones de Monitoreo',
            },
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ESCANEO', 'Escaneo de Sistema'), ('ACTUALIZACION', 'Actualización de Seguridad'), ('ALERTA', 'Alerta de Seguridad'), ('CONFIGURACION', 'Cambio de Configuración')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='Crud.empresas')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-fecha'],
            },
        ),
    ]
